[package]
name = "nmcurse"
version = "0.1.0"
edition = "2021"

[dependencies]
ncurses = "5.101.0"
libc = "0.2"
cc = "1.0.18"
pkg-config = "0.3"
zeroize = { version = "1.8.1", features = ["std"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
