[package]
name = "nmcurse"
version = "0.1.0"
edition = "2024"

[dependencies]
ncurses = "6.0.1"
libc = "0.2"
cc = "1.0.18"
pkg-config = "0.3"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
