name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.1)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install ncurses development libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Test version command
        run: |
          cargo build --release
          ./target/release/nmcurse --version
          ./target/release/nmcurse -v
          ./target/release/nmcurse --help

  build:
    name: Build for multiple platforms
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: nmcurse-linux-amd64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            artifact_name: nmcurse-linux-amd64-compat
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install ncurses development libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Test binary
        run: |
          ./target/${{ matrix.target }}/release/nmcurse --version
          echo "Binary test passed"

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Copy binary to artifacts
        run: |
          cp target/${{ matrix.target }}/release/nmcurse artifacts/${{ matrix.artifact_name }}
          chmod +x artifacts/${{ matrix.artifact_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: artifacts/${{ matrix.artifact_name }}

  create-release:
    name: Create GitHub Release
    needs: [check, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "tag=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create release notes
        run: |
          echo "# Release ${{ steps.version.outputs.version }}" > release_notes.md
          echo "" >> release_notes.md
          echo "## What's Changed" >> release_notes.md
          echo "- Build artifacts for Linux x86_64" >> release_notes.md
          echo "- Version ${{ steps.version.outputs.version }} of nmcurse" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Installation" >> release_notes.md
          echo "Download the appropriate binary for your system:" >> release_notes.md
          echo "- \`nmcurse-linux-amd64\` - For modern Linux systems" >> release_notes.md
          echo "- \`nmcurse-linux-amd64-compat\` - For older Linux systems (Ubuntu 20.04)" >> release_notes.md
          echo "" >> release_notes.md
          echo "Make the binary executable: \`chmod +x nmcurse-*\`" >> release_notes.md

      - name: Create or update tag (for workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.version.outputs.tag }} -m "Release ${{ steps.version.outputs.version }}"
          git push origin ${{ steps.version.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            nmcurse-linux-amd64/nmcurse-linux-amd64
            nmcurse-linux-amd64-compat/nmcurse-linux-amd64-compat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
